### ISSUE TITLE
Manage transcript mapping sources

### ISSUE THREAD

**Issue by martijnvermaat** [mutalyzer/ansible-role-mutalyzer#6]
Not sure if it is really a good idea to manage this with Ansible (we currently do this by hand)

We can now import LRG transcript mappings from the NCBI (with mutalyzer/mutalyzer#147), which are updated daily. So it makes sense to setup a cron job for this using Ansible.

For the NCBI mapview import, I think we should configure the mapview files in Ansible and they are downloaded and imported at playbook run. Of course this can be optimized by keeping the downloaded file and only doing this when we configure a new file that isn't yet downloaded. Downside is still that importing takes a very long time, so whenever there is a new mapview release the Ansible run would take very long as well.

ftp://ftp.ebi.ac.uk/pub/databases/lrgex/list_LRGs_transcripts_GRCh37.txt
https://gist.github.com/martijnvermaat/ce84945d05b4e42d3584

**Comment by martijnvermaat** [comment]
From a user perspective, a configuration like the following would be nice:

```
mutalyzer_assemblies:
  - definition: https://raw.githubusercontent.com/mutalyzer/mutalyzer/master/extras/assemblies/GRCh37.json
    mappings:
      - type: mapview
        file: ftp://ftp.ncbi.nlm.nih.gov/genomes/MapView/Homo_sapiens/sequence/ANNOTATION_RELEASE.105/initial_release/seq_gene.md.gz
        group_label: GRCh37.p13-Primary Assembly
        schedule: once
      - type: reference
        accession: NC_012920.1
        schedule: once
      - type: lrgmap
        file: ftp://ftp.ebi.ac.uk/pub/databases/lrgex/list_LRGs_transcripts_GRCh37.txt
        schedule: weekly
```

But it will be quite some work to implement and has some problems:
- We should probably store the definition (as a cache, to make sure an assembly is only added once), but under what name?
- Where to store the mapview files?
- How to know the name or alias for the assembly (needed for importing)? It is in the definition file.
